### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [jmplonka/Importer3D#1]
Hello, under what license is this project released under ? I would like to study it to learn Freecad scripting. Thank-you.

**Comment by berylliumquestion** [comment]
I too would like to know what license you would release this under. I'm curious about the different types of 3d objects out there.

**Comment by jmplonka** [comment]
It is free software in terms of the [GNU General Public License](https://de.wikipedia.org/wiki/GNU_General_Public_License)
This should allow you to reuse and study my code as long as you don't "forget" to remember me :)
