### ISSUE TITLE
blender add-on

### ISSUE THREAD

**Issue by ghost** [jmplonka/Importer3D#13]
Hi

Are you interested to reuse the python code to make a Blender add-on to import those files into Blender?

**Comment by jmplonka** [comment]
Hi,
Blender is a great tool - indeed. But I don't have any knowledge about it's API.
Maybe there is someone out there, with more time to make it a blender plugin.

Sorry.

**Comment by nrgsille76** [comment]
> Hi, Blender is a great tool - indeed. But I don't have any knowledge about it's API. Maybe there is someone out there, with more time to make it a blender plugin.
> 
> Sorry.

Hi,
I have made this job: [Blender max importer extension](https://github.com/nrgsille76/io_scene_max)
