### ISSUE TITLE
<class 'AttributeError'>: 'UnknownChunk' object has no attribute 'mdata'

### ISSUE THREAD

**Issue by jsmaniac** [jmplonka/Importer3D#4]
Hi! An error from this plug-in was reported in the forum https://forum.freecadweb.org/viewtopic.php?f=22&t=54555, thought you'd want to know :)

The reporter attached a .zip with the .3DS and .LWO files there (I won't copy them here as I don't know if they contain any copyrighted content, sorry)

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\FreeCAD 0.18\Mod\Arch\import3DS.py", line 72, in insert
    read(filename)
  File "C:\Program Files\FreeCAD 0.18\Mod\Arch\import3DS.py", line 92, in read
    for j,d_nobj in enumerate(dom.mdata.objects):
<class 'AttributeError'>: 'UnknownChunk' object has no attribute 'mdata'
```

Cheers!

**Comment by jmplonka** [comment]
Work started...

**Comment by jmplonka** [comment]
Several reasons led to the crach
- wrong endianness
- optional information assumed to be mendatory
- ...
But should be fixed now! The given examples are shown.
