### ISSUE TITLE
Installing as an Addon

### ISSUE THREAD

**Issue by janzboril** [jmplonka/Importer3D#5]
Hello guys, I tried to install Importer3D to my Bledner but I am doing probably something wrong. I tried many ways of installing it but I still can't find any way how to turn on it as an addon or to have an option in Import row.
Can you please give me an advice how to solve my problem? :)
Thanks a lot!

**Comment by jmplonka** [comment]
Sorry, but this was never intended to be a plugin for Blender, but for FreeCAD. Maybe someone is able to write a wrapper or port for Blender.
Jens
